language: ruby
os: osx
env: OSX=10.11
osx_image: xcode7.3
rvm: system

before_install:
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - sudo chown -R $USER "$(brew --repo)"
  - git -C "$(brew --repo)" reset --hard origin/master
  - git -C "$(brew --repo)" clean -qxdff
  - brew update
  - rm -rf "$(brew --repo $TRAVIS_REPO_SLUG)"
  - mkdir -p "$(brew --repo $TRAVIS_REPO_SLUG)"
  - rsync -az "$TRAVIS_BUILD_DIR" "$(brew --repo $TRAVIS_REPO_SLUG)"
  - export TRAVIS_BUILD_DIR="$(brew --repo $TRAVIS_REPO_SLUG)"
  - cd "$(brew --repo $TRAVIS_REPO_SLUG)"

install:
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

script:
  - brew test-bot --tap=homebrew/core

notifications:
  slack:
    secure: lx4hvqKGzMHTl/Y5+AR58uhJpeoPPCUlKPfcnjW4rQjEp/834B2DQnJiyztvfNjm95LTOAJUJmpHKrF4bEokwRHaZY+dywI93yle6Nm185gIr6krXymrUDG8aSsOIFbr9dDHWFDxRMzOOyF/gAJxLrg0kt/R5ZoS33es0Y98KLd9Ebgm4+NDKjl1R67ZgVzqH0uDg7wNHCY/aAkIx27d8xTMgDxHnu82p4gmPn74obPCUNoBL1pqOvOj+WFlLSD9SH2s28yh2OU9suIPrCAQgcKM6IrLQqaupTQSW7T4Y2XJXMe8h+UxfFV0ha8NbOietZlHEzRvQ9B7tPhkDsSKaTb9D78/mRHL5w0ldo8wjT2feLcn+GW9Qss2g6VAkMNfwBPdRWtevHCm866xv1SXYCVCjIsLFTOnv1lxUCDB401dn7ircKB8Zq7TOj31k/MJgh96SKQJYX+TREHHoBGL/+mlat4M7wX7LS/CKV55rKdqkT3qdensLClr7xFMRYshqo5qhGBDOsMLVu39VSZBA2vCpEFWfgJE1PbtgYHPgUKtD91lbhR5VZP73k4dM8MZyMOzRv4sRNw4XKyRqmQczhD0sPvTYPVRsvBDTb/0Zl5F6IOzIQhb1O176yi9cWw4xheioaiUqXUQIW/XUshj86htiAGS3+6uGN+Y1tEWVW0=
  email:
    on_success: never
    on_failure: always
