name: Bump formulae on schedule or request

on:
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every day at 5am
    - cron: '0 5 * * *'

env:
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
  FORMULAE: >
    abcmidi
    ack
    activemq
    alda
    aliddns
    aliyun-cli
    allure
    alluxio
    ammonite-repl
    angular-cli
    annie
    ansible-lint
    ant
    ant@1.9
    anycable-go
    apache-archiva
    apache-drill
    apache-flink
    apache-geode
    apache-opennlp
    apache-spark
    apidoc
    apktool
    arb
    argo
    argocd
    argocd-autopilot
    argocd-vault-plugin
    arkade
    armadillo
    arrayfire
    artifactory
    asciidoctorj
    ask-cli
    assh
    asuka
    asymptote
    atlantis
    atuin
    autorest
    autorestic
    avrdude
    aws-cdk
    aws-elasticbeanstalk
    aws-es-proxy
    azcopy
    b3sum
    bagit
    baidupcs-go
    ballerina
    bash_unit
    batik
    bazel
    bazelisk
    bbtools
    bcoin
    bear
    benthos
    berglas
    bettercap
    bigloo
    binaryen
    bnd
    bosh-cli
    bottom
    brew-php-switcher
    brook
    broot
    bubblewrap
    buildifier
    buildkit
    buildozer
    buildpulse-test-reporter
    buku
    bundletool
    bupstash
    butane
    byacc
    byteman
    bzt
    caddy
    cadence
    cadence-workflow
    caire
    calicoctl
    cargo-audit
    cargo-bloat
    cargo-c
    cargo-edit
    cargo-instruments
    cargo-llvm-lines
    cargo-outdated
    cargo-watch
    carrot2
    cassandra
    cassandra-reaper
    catch2
    cdk8s
    cfr-decompiler
    cfssl
    cgl
    chamber
    charmcraft
    cheat
    checkstyle
    chezmoi
    choose-rust
    chromaprint
    chronograf
    cilium-cli
    circleci
    clair
    clamav
    clarinet
    clash
    clazy
    cliclick
    clojurescript
    closure-compiler
    cloud-nuke
    cloudflare-wrangler
    cloudformation-guard
    clusterctl
    cobalt
    code-minimap
    cointop
    coinutils
    colima
    composer
    condure
    conftest
    consul
    consul-template
    contentful-cli
    convox
    copilot
    coredns
    cortex
    cosign
    couchdb
    croc
    cromwell
    crowdin
    crun
    css-crush
    csvtk
    cubejs-cli
    cweb
    cypher-shell
    dafny
    darkstat
    datree
    dbdeployer
    ddrescue
    deark
    delve
    deno
    dependency-check
    derby
    detekt
    detox
    devspace
    dex2jar
    diamond
    diesel
    diffoscope
    digdag
    django-completion
    djl-serving
    dnscontrol
    dnscrypt-proxy
    dnsx
    docfx
    docker
    docker-compose
    docker-compose-completion
    docker-credential-helper
    docker-slim
    docker-squash
    doctl
    docuum
    dolt
    dosbox-staging
    dotenv-linter
    double-conversion
    doxygen
    dprint
    driftctl
    drill
    drone-cli
    druid
    dstask
    dua-cli
    duckscript
    dune
    dust
    dvc
    easyengine
    efm-langserver
    ehco
    eksctl
    elan-init
    elasticsearch@6
    elfutils
    elixir
    embulk
    emscripten
    envconsul
    envoy
    esbuild
    eslint
    esptool
    etcd
    ethereum
    exploitdb
    faas-cli
    fabric-installer
    fantom
    faudio
    fblog
    fdroidserver
    feh
    fennel
    feroxbuster
    ffsend
    firebase-cli
    firefoxpwa
    flank
    flarectl
    fleet-cli
    flow-cli
    fluent-bit
    flume
    fluxctl
    flyway
    fmt
    fn
    fop
    ford
    fortio
    frugal
    fselect
    func-e
    fuse-overlayfs
    fuseki
    futhark
    gatsby-cli
    gau
    gdu
    geeqie
    geph4
    gerbil-scheme
    gh
    ghz
    ghz-web
    gifski
    ginac
    git-annex
    git-cliff
    git-delta
    git-lfs
    git-town
    gitbackup
    gitbucket
    gitlab-runner
    gitleaks
    gitql
    glassfish
    gleam
    global
    glooctl
    gmailctl
    gmic
    gmsh
    gnunet
    gnupg-pkcs11-scd
    gnuplot
    go-md2man
    go@1.16
    gofumpt
    gojq
    golang-migrate
    golangci-lint
    google-java-format
    goose
    gopass
    gopls
    gor
    goredo
    goreleaser
    goreman
    gosec
    gostatic
    govc
    gowsdl
    gpg-tui
    gradle
    gradle-completion
    gradle-profiler
    grafana
    grails
    grin
    gromacs
    groovy
    groovysdk
    gsoap
    gupnp-tools
    hadoop
    halide
    hapi-fhir-cli
    hasura-cli
    hcloud
    helm
    helmfile
    helmsman
    hexyl
    hidapi
    himalaya
    hive
    hivemind
    htmldoc
    htmlq
    htmltest
    htpdate
    httpx
    hyperfine
    iamy
    igv
    imagemagick
    imagemagick@6
    imap-backup
    imgproxy
    influxdb
    influxdb-cli
    influxdb@1
    inlets
    ioctl
    ipinfo-cli
    ipmiutil
    ipopt
    ircd-hybrid
    istioctl
    ivy
    jadx
    java-service-wrapper
    jena
    jenkins
    jenkins-job-builder
    jenkins-lts
    jetty
    jfrog-cli
    jhipster
    jmeter
    jnethack
    jql
    jruby
    jsonnet
    jsonschema
    jsvc
    juju
    just
    k2tf
    k3d
    k3sup
    k6
    k9s
    kafka
    kahip
    kalker
    kamel
    kapacitor
    kcptun
    keptn
    kepubify
    keydb
    ki
    kickstart
    kind
    kitchen-sync
    kn
    knot
    knot-resolver
    ko
    kompose
    kops
    kotlin
    krew
    ktlint
    kube-aws
    kube-linter
    kubeaudit
    kubebuilder
    kubecfg
    kubecm
    kubeconform
    kubeless
    kubeprod
    kubergrunt
    kubernetes-cli
    kubernetes-service-catalog-client
    kubeseal
    kubespy
    kubevela
    kubie
    kumactl
    kustomize
    kyma-cli
    languagetool
    latex2html
    latexml
    lazydocker
    lean-cli
    lefthook
    lego
    leiningen
    lexbor
    libdap
    libgetdata
    libgr
    libnfs
    liboqs
    libpano
    libpipeline
    librdkafka
    librespot
    lima
    linkerd
    liquibase
    lmod
    localstack
    log4cxx
    lout
    lychee
    macchina
    mage
    mailutils
    mapcidr
    marked
    marp-cli
    matterbridge
    maven
    mavsdk
    maxwell
    mdbook
    mdcat
    mdzk
    meilisearch
    memcached
    mesa
    meson
    metabase
    micro
    micronaut
    mill
    minikube
    miniserve
    mitmproxy
    mmark
    mmctl
    moar
    mockery
    moco
    molecule
    mongocli
    monolith
    moto
    mpv
    muffet
    murex
    mypy
    naabu
    nanoflann
    nativefier
    nats-server
    nats-streaming-server
    navi
    ncspot
    neo4j
    neofetch
    nest
    netlify-cli
    newrelic-cli
    nexus
    nfpm
    nng
    node_exporter
    node-sass
    nomad
    notcurses
    nsq
    nuclei
    numcpp
    nushell
    oauth2_proxy
    ocaml-findlib
    oci-cli
    ocp
    ocrmypdf
    octant
    octave
    oha
    okteto
    omniorb
    onednn
    onedrive
    onscripter
    ooniprobe
    opa
    openrtsp
    opensearch
    operator-sdk
    oras
    orc-tools
    orientdb
    ortp
    osm
    oxipng
    pacapt
    packer
    packr
    payara
    pdftk-java
    pdm
    pgloader
    pgweb
    phoronix-test-suite
    php-code-sniffer
    php-cs-fixer
    phpmd
    phpmyadmin
    phpstan
    pianod
    picard-tools
    pig
    pillow
    plantuml
    plow
    pmd
    pngquant
    pnpm
    pocsuite3
    podman
    pre-commit
    prestd
    presto
    principalmapper
    procs
    protoc-gen-go-grpc
    psalm
    pueue
    pushpin
    pwntools
    py-spy
    pyflow
    pyoxidizer
    qjackctl
    qpid-proton
    questdb
    rancher-cli
    rav1e
    rbspy
    rbw
    rclone
    rebar3
    recode
    regina-rexx
    reminiscence
    reposurgeon
    revive
    rhit
    riemann
    rke
    rollup
    rosa-cli
    rpg-cli
    rqlite
    rubberband
    rustup-init
    s-search
    s2n
    saml2aws
    sbt
    scala
    scorecard
    scotch
    scummvm
    scummvm-tools
    scw
    sdl2
    seaweedfs
    selene
    selenium-server
    seqkit
    ser2net
    server-go
    serverless
    shadowenv
    sheldon
    shellharden
    shellz
    shfmt
    silicon
    singularity
    sjk
    skaffold
    skopeo
    slackcat
    sleuthkit
    slides
    smimesign
    sn0int
    sniffer
    sniffglue
    solana
    solr
    solr@7.7
    sonarqube
    sonobuoy
    sponge
    spotbugs
    spotify-tui
    sqlancer
    sqlc
    sqlmap
    sqlx-cli
    sslyze
    stanford-corenlp
    starship
    statix
    stdman
    step
    storm
    streamlink
    stress-ng
    structurizr-cli
    stunnel
    subversion
    sundials
    suricata
    svgbob
    svgo
    svtplay-dl
    swagger-codegen
    swagger-codegen@2
    syncthing
    talisman
    tanka
    tcsh
    tctl
    tealdeer
    tectonic
    tektoncd-cli
    teleport
    tendermint
    tengo
    termshark
    terracognita
    terraform-inventory
    terraform-ls
    terraform-provider-libvirt
    terraform-rover
    terraformer
    terragrunt
    terrascan
    tfsec
    thanos
    thrift
    tika
    tile38
    tm
    toast
    tomcat
    tomcat-native
    tomcat@8
    tomcat@9
    tomee-plus
    tomee-webprofile
    topgrade
    traefik
    traefik@1
    trafficserver
    tree-sitter
    trino
    trojan-go
    typedb
    tz
    uni
    universal-ctags
    v2ray
    vale
    vault
    vault-cli
    veclibfort
    velero
    vercel-cli
    vgrep
    virgil
    virustotal-cli
    vite
    vitess
    vivid
    vnstat
    volta
    vpn-slice
    vsearch
    vsh
    vue-cli
    wabt
    wakatime-cli
    wallpaper
    wasm-pack
    wasmer
    wasmtime
    watchexec
    waypoint
    webp
    webpack
    websocat
    webtorrent-cli
    wgcf
    whistle
    whois
    wildfly-as
    wiremock-standalone
    wolfssl
    xalan-c
    xcbeautify
    xclogparser
    xerces-c
    xgboost
    xh
    xplr
    xray
    yaegi
    ykman
    yosys
    youtubedr
    yq
    z3
    zbctl
    zellij
    zola
    zookeeper
    zoxide
    zstd

jobs:
  autobump:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu16.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Bump formulae
        uses: Homebrew/actions/bump-formulae@master
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_CORE_REPO_WORKFLOW_TOKEN }}
          formulae: ${{ github.event.inputs.formulae || env.FORMULAE }}
