name: GitHub Actions CI
on:
  pull_request:
    paths:
      - "Formula/alsa-lib.rb"
      - "Formula/device-mapper.rb"
      - "Formula/libaio.rb"
      - "Formula/ladspa-sdk.rb"
      - "Formula/libbsd.rb"
      - "Formula/libcap.rb"
      - "Formula/libdrm.rb"
      - "Formula/libfuse.rb"
      - "Formula/libmnl.rb"
      - "Formula/libnetfilter-queue.rb"
      - "Formula/libnfnetlink.rb"
      - "Formula/libpciaccess.rb"
      - "Formula/libseccomp.rb"
      - "Formula/linux-headers.rb"
      - "Formula/strace.rb"
jobs:
  tests_linux:
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      HOMEBREW_CORE_GIT_REMOTE: ${{github.event.repository.html_url}}
      HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-formulae
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae
