name: Triage tasks

on: pull_request_target

concurrency:
  group: "triage-${{ github.event.number }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-22.04
    steps:
      - name: Check commit format
        uses: Homebrew/actions/check-commit-format@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}

      - name: Label pull request
        uses: Homebrew/actions/label-pull-requests@master
        if: always()
        with:
          token: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}
          def: |
            - label: workflows
              path: .github/workflows/.+

            - label: new formula
              status: added
              path: Formula/.+

            - label: marked for removal/rejection
              status: removed
              path: Formula/.+

            - label: bottle unneeded
              path: Formula/.+
              content: \n  (bottle :unneeded)\n

            - label: no ARM bottle
              path: Formula/.+
              content: '\n    sha256.* big_sur: +"[a-fA-F0-9]+"\n'
              missing_content: '\n    sha256.* arm64_big_sur: +"[a-fA-F0-9]+"\n'

            - label: no Linux bottle
              path: Formula/.+
              content: \n  bottle do\n
              missing_content:
                - '\n    sha256.* x86_64_linux: +"[a-fA-F0-9]+"\n'
                - '\n    sha256.* all: +"[a-fA-F0-9]+"\n'
                - depends_on :macos

            - label: formula deprecated
              path: Formula/.+
              content: \n  deprecate!.*\n

            - label: formula disabled
              path: Formula/.+
              content: \n  disable!.*\n

            - label: legacy
              path: Formula/.+@.+
              except:
                - Formula/bash-completion@2.rb
                - Formula/openssl@1.1.rb
                - Formula/openssl@3.rb
                - Formula/postgresql@15.rb
                - Formula/python@3.11.rb
                - Formula/python-gdbm@3.11.rb
                - Formula/python-tk@3.11.rb

            - label: missing license
              path: Formula/.+
              missing_content: \n  license .+\n

            - label: deprecated license
              path: Formula/.+
              content: license .*"(GPL|LGPL|AGPL|GFDL)-[0-9].[0-9][+]?".*

            - label: boost
              path: Formula/.+
              content: depends_on "boost(@[0-9.]+)?"

            - label: ffmpeg
              path: Formula/.+
              content: depends_on "ffmpeg(@[0-9.]+)?"

            - label: go
              path: Formula/.+
              content: depends_on "go(@[0-9.]+)?"

            - label: haskell
              path: Formula/.+
              content: depends_on "(ghc|haskell-stack)(@[0-9.]+)?"

            - label: icu4c
              path: Formula/.+
              content: depends_on "icu4c(@[0-9.]+)?"

            - label: java
              path: Formula/.+
              content: depends_on "openjdk(@[0-9.]+)?"

            - label: linux-only
              path: Formula/.+
              content: depends_on :linux

            - label: macos-only
              path: Formula/.+
              content: depends_on :macos

            - label: lua
              path: Formula/.+
              content: depends_on "(lua|luajit|luajit-openresty)(@[0-9.]+)?"

            - label: nodejs
              path: Formula/.+
              content: depends_on "node(@[0-9.]+)?"

            - label: ocaml
              path: Formula/.+
              content: depends_on "ocaml(@[0-9.]+)?"

            - label: perl
              path: Formula/.+
              content: (depends_on|uses_from_macos) "perl(@[0-9.]+)?"

            - label: php
              path: Formula/.+
              content: (depends_on|uses_from_macos) "php(@[0-9.]+)?"

            - label: python
              path: Formula/.+
              content: (depends_on|uses_from_macos) "python(@[0-9.]+)?"
              missing_content: (depends_on|uses_from_macos) "python(@[0-9.]+)?" => \[?:(build|test)

            - label: ruby
              path: Formula/.+
              content: (depends_on|uses_from_macos) "ruby(@[0-9.]+)?"

            - label: rust
              path: Formula/.+
              content: depends_on "rust(@[0-9.]+)?"

            - label: dotnet
              path: Formula/.+
              content: depends_on "dotnet(@[0-9.]+)?"

            - label: swift
              path: Formula/.+
              content: system "swift", "build"

            - label: long build
              path: Formula/(agda|arangodb|boost|deno|dotnet|emscripten|gcc|ghc|llvm|node|pango|ponyc|rust|suite-sparse|swift|texlive|qt|v8)(@[0-9]+)?.rb
              keep_if_no_match: true

            - label: CI-build-dependents-from-source
              path: Formula/(cabal-install|docbook-xsl|emscripten|erlang|ghc|go|ocaml|ocaml-findlib|ocaml-num|openjdk|rust).rb
              keep_if_no_match: true

            - label: CI-skip-recursive-dependents
              path: Formula/(gettext|openssl@(3|1.1)|sqlite).rb
              keep_if_no_match: true

            - label: CI-linux-self-hosted
              path: Formula/(gdbm|llvm|openssl@1.1|python@3.10|qt(@5)?).rb
              keep_if_no_match: true

            - label: bump-formula-pr
              pr_body_content: Created with `brew bump-formula-pr`
